name: JMeter Tests

on: [push, pull_request]

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install JMeter
        run: |
          JMETER_VERSION=5.6.3
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xvzf apache-jmeter-$JMETER_VERSION.tgz
          mv apache-jmeter-$JMETER_VERSION $HOME/jmeter
          echo "$HOME/jmeter/bin" >> $GITHUB_PATH

      - name: Run JMeter test
        run: |
          jmeter -n -t jmeter-tests/Publish.jmx -l results_publish.jtl -j jmeter.log

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: |
            results_publish.jtl
            jmeter.log
